-- Masukkan proyek kustom 'hyrjy' dan seluruh portofolio ke database 'sotardoc_projects'
INSERT INTO `projects` (
  `id`, `title`, `category`, `image_url`, `summary`, `description`, `client`, `duration`,
  `architecture`, `metrics`, `tech_stack`, `live_url`, `is_active`, `sort_order`
) VALUES 
(
  'hyrjy-6859',
  'hyrjy',
  'AI & Machine Learning',
  '/uploads/project_1790074247533_screen.png',
  'khkh',
  'hghhyn',
  'jhgjgh',
  '3 Bulan',
  '["jghjgfj"]',
  '[{"label":"hgjg","value":"jgjg"}]',
  '["jgjg"]',
  '',
  1,
  0
),
(
  '0',
  'AgriFlow-ML',
  'Machine Learning & Smart Agriculture',
  '/projects/card-agriflow.svg',
  'Sistem analitik prediksi hasil panen dan deteksi dini anomali tanaman berbasis citra satelit dan sensor IoT.',
  'Platform kecerdasan buatan berbasis multi-spectral imagery dan jaringan sensor nirkabel LoRaWAN. Menganalisis kelembapan tanah, kesehatan vegetasi (NDVI index), dan memprediksi volume panen dengan akurasi hingga 94.2%.',
  'AgroNusantara Corp',
  '4 Bulan',
  '["Edge AI Gateway (YOLOv8 & PyTorch)","Time-Series Database (TimescaleDB)","Kubernetes Cluster Microservices","Grafana Observability Stack"]',
  '[{"label":"Akurasi Prediksi","value":"94.2%"},{"label":"Efisiensi Air","value":"35%"},{"label":"Area Termonitor","value":"12.000 Ha"}]',
  '["Python","PyTorch","Next.js 14","FastAPI","TimescaleDB","Docker","LoRaWAN"]',
  'https://demo.sotardoc.com/agriflow',
  1,
  1
),
(
  '1',
  'VisionScan OCR & KYC',
  'Computer Vision & Identity Fraud Detection',
  '/projects/card-ocr.svg',
  'Otomasi verifikasi identitas (e-KYC) dengan pengenalan teks KTP berkecepatan tinggi dan biometrik anti-spoofing.',
  'Solusi machine vision enterprise untuk membaca, mengekstrak, dan memvalidasi dokumen identitas resmi (KTP, SIM, Paspor) dalam waktu < 450ms.',
  'FinTech Mitra Utama',
  '3 Bulan',
  '["Deep Learning OCR Pipeline (CRNN + CTC)","3D Liveness Face Matching","Event-Driven RabbitMQ Queue","Encrypted Data Vault (AES-256)"]',
  '[{"label":"Waktu Verifikasi","value":"< 450ms"},{"label":"Akurasi OCR","value":"99.1%"},{"label":"Fraud Ditekan","value":"87%"}]',
  '["OpenCV","TensorFlow Serving","Go (Golang)","React","PostgreSQL","Redis"]',
  'https://demo.sotardoc.com/visionscan',
  1,
  2
),
(
  '2',
  'MediTrack Transformation',
  'Healthcare Infrastructure Migration',
  '/projects/card-meditrack.svg',
  'Modernisasi arsitektur SIMRS rumah sakit dari sistem monolitik menuju microservices berbasis Kubernetes tanpa downtime.',
  'Migrasi infrastruktur kritis rumah sakit kelas A dengan 1.200 tempat tidur dan 45 modul fungsional.',
  'RSUD Sehat Mandiri',
  '6 Bulan',
  '["Strangler Fig Pattern Migration","Dual-Write CDC (Debezium + Kafka)","Zero-Downtime Blue/Green Deploy","HIPAA/GDPR Compliant Vault"]',
  '[{"label":"Downtime Selama Migrasi","value":"0 Detik"},{"label":"Peningkatan Transaksi","value":"3.2x"},{"label":"Response Time","value":"85ms"}]',
  '["Kubernetes","Apache Kafka","Node.js / Express","PostgreSQL","Terraform","Prometheus"]',
  '',
  1,
  3
),
(
  '3',
  'BankCore Kubernetes Migration',
  'Cloud Native & Enterprise Core Banking',
  '/projects/card-bankcore.svg',
  'Arsitektur cloud-native berstandar perbankan dengan sertifikasi kepatuhan PCI-DSS dan replikasi multi-region.',
  'Implementasi platform runtime enterprise banking dengan ketahanan 99.999% SLA, isolasi jaringan berbasis Cilium eBPF, dan audit trail otomatis.',
  'Bank Multi Regional Tbk',
  '8 Bulan',
  '["Multi-AZ Hybrid Cloud Setup","Cilium eBPF Service Mesh","HashiCorp Vault HSM Integration","Automated Chaos Engineering"]',
  '[{"label":"SLA Availability","value":"99.999%"},{"label":"Throughput Transaksi","value":"15.000 TPS"},{"label":"Audit Compliance","value":"100%"}]',
  '["Go","Kubernetes","gRPC","HashiCorp Vault","Cilium eBPF","Elastic APM"]',
  '',
  1,
  4
),
(
  '4',
  'Parkarejo',
  'Enterprise Logistics & Urban Mobility',
  '/projects/card-parkarejo.svg',
  'Platform manajemen logistik cerdas dan pelacakan armada armada kargo real-time dengan routing dinamis hemat bahan bakar.',
  'Sistem integrasi IoT armada skala nasional yang menghubungkan 500+ unit truk kontainer dengan dispatch engine pintar.',
  'PT Trans Nusantara Logistik',
  '5 Bulan',
  '["Dynamic VRP Routing Engine (OR-Tools)","MQTT Telematics Ingestion Broker","Geofencing & Anomaly Alerts","Progressive Web App Offline First"]',
  '[{"label":"Penghematan BBM","value":"18.4%"},{"label":"On-Time Delivery","value":"98.7%"},{"label":"Armada Aktif","value":"500+ Unit"}]',
  '["TypeScript","Vue.js","Go","MongoDB","Mosquitto MQTT","Mapbox GL"]',
  'https://parkarejo.id',
  1,
  5
),
(
  '5',
  'NexaPay FinTech SuperApp',
  'Next-Gen Financial Application Design',
  '/projects/card-nexapay.svg',
  'Desain antarmuka dompet digital dan investasi mikro berfokus pada conversion rate tinggi dan kemudahan pengguna lintas generasi.',
  'Perancangan sistem desain komprehensif (300+ token komponen) untuk ekosistem superapp finansial inklusif.',
  'Nexa Digital Ventura',
  '2.5 Bulan',
  '["Atomic Design System Architecture","WCAG 2.1 AA Accessibility Tested","Micro-Interactions Animation Kit","Design Token Pipeline to Code"]',
  '[{"label":"Peningkatan Konversi","value":"+42%"},{"label":"Waktu Onboarding","value":"< 60 Detik"},{"label":"App Rating","value":"4.9 / 5.0"}]',
  '["Figma Tokens","Tailwind CSS","Framer Motion","React Native","Storybook"]',
  'https://nexapay.sotardoc.com',
  1,
  6
)
ON DUPLICATE KEY UPDATE title = VALUES(title);
